In [51]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

In [ ]:
df = pd.read_csv('../data/brain_tumor_dataset.csv')
df.head()

In [54]:
df.drop(columns=['Patient_ID'], inplace=True)

In [55]:
num_cols = ['Age', 'Tumor_Size', 'Survival_Rate', 'Tumor_Growth_Rate']
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])
df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1.355253,Male,Malignant,0.050488,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,No,No,No,-1.089675,-1.717548,No,Positive,Yes
1,-1.347627,Male,Benign,-0.141399,Parietal,Glioblastoma,II,Headache,Headache,Nausea,Yes,Yes,Yes,-1.375673,0.739298,Yes,Positive,Yes
2,-1.060087,Male,Benign,0.127742,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,No,No,No,-1.335202,0.402556,No,Negative,No
3,-1.175103,Male,Malignant,-1.379648,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,Yes,No,Yes,-1.058346,-0.316229,Yes,Negative,No
4,0.262599,Female,Benign,-1.023511,Parietal,Glioblastoma,I,Headache,Headache,Seizures,No,No,Yes,-0.893014,0.624153,No,Positive,Yes

In [56]:
le = LabelEncoder()
le_cols = ['Gender', 'Family_History', 'MRI_Result',
           'Follow_Up_Required', 'Radiation_Treatment', 'Surgery_Performed', 'Chemotherapy']

for col in le_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1.355253,1,Malignant,0.050488,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,0,0,0,-1.089675,-1.717548,0,1,1
1,-1.347627,1,Benign,-0.141399,Parietal,Glioblastoma,II,Headache,Headache,Nausea,1,1,1,-1.375673,0.739298,1,1,1
2,-1.060087,1,Benign,0.127742,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,0,0,0,-1.335202,0.402556,0,0,0
3,-1.175103,1,Malignant,-1.379648,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,1,0,1,-1.058346,-0.316229,1,0,0
4,0.262599,0,Benign,-1.023511,Parietal,Glioblastoma,I,Headache,Headache,Seizures,0,0,1,-0.893014,0.624153,0,1,1

In [57]:
onehot_cols = ['Location', 'Histology', 'Symptom_1', 'Symptom_2', 'Symptom_3']
df = pd.get_dummies(df, columns=onehot_cols, drop_first=True, dtype=int)

df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Stage,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,...,Histology_Meningioma,Symptom_1_Nausea,Symptom_1_Seizures,Symptom_1_Vision Issues,Symptom_2_Nausea,Symptom_2_Seizures,Symptom_2_Vision Issues,Symptom_3_Nausea,Symptom_3_Seizures,Symptom_3_Vision Issues
0,1.355253,1,Malignant,0.050488,III,0,0,0,-1.089675,-1.717548,...,0,0,0,1,0,1,0,0,1,0
1,-1.347627,1,Benign,-0.141399,II,1,1,1,-1.375673,0.739298,...,0,0,0,0,0,0,0,1,0,0
2,-1.060087,1,Benign,0.127742,I,0,0,0,-1.335202,0.402556,...,1,0,0,1,0,0,0,0,1,0
3,-1.175103,1,Malignant,-1.379648,IV,1,0,1,-1.058346,-0.316229,...,0,0,0,1,0,1,0,0,0,0
4,0.262599,0,Benign,-1.023511,I,0,0,1,-0.893014,0.624153,...,0,0,0,0,0,0,0,0,1,0

In [58]:
roman_to_int = {'I': 1, 'II': 2, 'III': 3, 'IV': 4}
df['Stage'] = df['Stage'].map(roman_to_int)

df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Stage,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,...,Histology_Meningioma,Symptom_1_Nausea,Symptom_1_Seizures,Symptom_1_Vision Issues,Symptom_2_Nausea,Symptom_2_Seizures,Symptom_2_Vision Issues,Symptom_3_Nausea,Symptom_3_Seizures,Symptom_3_Vision Issues
0,1.355253,1,Malignant,0.050488,3,0,0,0,-1.089675,-1.717548,...,0,0,0,1,0,1,0,0,1,0
1,-1.347627,1,Benign,-0.141399,2,1,1,1,-1.375673,0.739298,...,0,0,0,0,0,0,0,1,0,0
2,-1.060087,1,Benign,0.127742,1,0,0,0,-1.335202,0.402556,...,1,0,0,1,0,0,0,0,1,0
3,-1.175103,1,Malignant,-1.379648,4,1,0,1,-1.058346,-0.316229,...,0,0,0,1,0,1,0,0,0,0
4,0.262599,0,Benign,-1.023511,1,0,0,1,-0.893014,0.624153,...,0,0,0,0,0,0,0,0,1,0