# 🏗️ 03 - Attribute Engineering

## 0. Introducción ⚙️
En este notebook se realiza la ingeniería de atributos sobre el dataset de tumores cerebrales previamente limpiado. El objetivo es transformar y codificar las variables para que sean aptas para el entrenamiento de modelos de machine learning.

## 1. Importación de Librerías y Carga de Datos 📚
Se importa pandas y las tecnicas de preprocesamiento del modulo `sklearn.preprocessing`. Además se carga el dataset procesado en la etapa anterior.

In [64]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

In [65]:
df = pd.read_csv('../data/brain_tumor_dataset.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/brain_tumor_dataset.csv'

## 2. Eliminación de Columnas Innecesarias 🚮
Identificamos las columnas innecesarias para nuestro procesamiento y el futuro entrenamiento de modelos y las eliminamos.

In [ ]:
df.drop(columns=['Patient_ID'], inplace=True)

## 3. Normalización de Variables Numéricas 🔢
Para estandarizar las variables numéricas, se utiliza la técnica StandardScaler, que transforma los valores de cada columna restando la media y dividiendo por la desviación estándar. Esto asegura que las características tengan media 0 y varianza 1, lo cual es fundamental para algoritmos que dependen de magnitudes como k-NN o regresión logística(modelo cual utilizaremos).
La transformación aplicada por `StandardScaler` se define matemáticamente como:

$$
z = \frac{x - \mu}{\sigma}
$$

Donde:

- \( x \) es el valor original
- \( \mu \) es la media de la característica
- \( \sigma \) es la desviación estándar de la característica

In [ ]:
num_cols = ['Age', 'Tumor_Size', 'Survival_Rate', 'Tumor_Growth_Rate']
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])
df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1.355253,Male,Malignant,0.050488,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,No,No,No,-1.089675,-1.717548,No,Positive,Yes
1,-1.347627,Male,Benign,-0.141399,Parietal,Glioblastoma,II,Headache,Headache,Nausea,Yes,Yes,Yes,-1.375673,0.739298,Yes,Positive,Yes
2,-1.060087,Male,Benign,0.127742,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,No,No,No,-1.335202,0.402556,No,Negative,No
3,-1.175103,Male,Malignant,-1.379648,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,Yes,No,Yes,-1.058346,-0.316229,Yes,Negative,No
4,0.262599,Female,Benign,-1.023511,Parietal,Glioblastoma,I,Headache,Headache,Seizures,No,No,Yes,-0.893014,0.624153,No,Positive,Yes

## 4. Codificación de Variables Categóricas 🏷️

Las variables categóricas nominales binarias se transforman mediante **Label Encoding**, asignando un valor numérico (0 o 1) a cada categoría. Esta técnica es eficiente para columnas con solo dos categorías, como 'Yes' / 'No', ya que evita la creación de múltiples columnas como en el One Hot Encoding.

Se utiliza `LabelEncoder` de `sklearn.preprocessing`, lo cual facilita la conversión de datos categóricos al formato requerido por algoritmos de aprendizaje automático.

In [ ]:
le = LabelEncoder()
le_cols = ['Gender', 'Family_History', 'MRI_Result',
           'Follow_Up_Required', 'Radiation_Treatment', 'Surgery_Performed', 'Chemotherapy']

for col in le_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Location,Histology,Stage,Symptom_1,Symptom_2,Symptom_3,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,Family_History,MRI_Result,Follow_Up_Required
0,1.355253,1,Malignant,0.050488,Temporal,Astrocytoma,III,Vision Issues,Seizures,Seizures,0,0,0,-1.089675,-1.717548,0,1,1
1,-1.347627,1,Benign,-0.141399,Parietal,Glioblastoma,II,Headache,Headache,Nausea,1,1,1,-1.375673,0.739298,1,1,1
2,-1.060087,1,Benign,0.127742,Parietal,Meningioma,I,Vision Issues,Headache,Seizures,0,0,0,-1.335202,0.402556,0,0,0
3,-1.175103,1,Malignant,-1.379648,Temporal,Medulloblastoma,IV,Vision Issues,Seizures,Headache,1,0,1,-1.058346,-0.316229,1,0,0
4,0.262599,0,Benign,-1.023511,Parietal,Glioblastoma,I,Headache,Headache,Seizures,0,0,1,-0.893014,0.624153,0,1,1

## 5. Codificación de Variables Categóricas Nominales con One Hot Encoding 0️⃣1️⃣

Para las variables categóricas con múltiples categorías posibles, como la localización del tumor, el tipo histológico y los síntomas, se utiliza **One Hot Encoding**. Esta técnica crea una columna binaria para cada categoría, permitiendo que los modelos interpreten correctamente la información sin asumir un orden implícito entre las categorías.

Se emplea la función `pd.get_dummies` de pandas, que genera automáticamente las columnas necesarias y asigna valores 0 o 1 según corresponda.

In [ ]:
onehot_cols = ['Location', 'Histology', 'Symptom_1', 'Symptom_2', 'Symptom_3']
df = pd.get_dummies(df, columns=onehot_cols, drop_first=True, dtype=int)

df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Stage,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,...,Histology_Meningioma,Symptom_1_Nausea,Symptom_1_Seizures,Symptom_1_Vision Issues,Symptom_2_Nausea,Symptom_2_Seizures,Symptom_2_Vision Issues,Symptom_3_Nausea,Symptom_3_Seizures,Symptom_3_Vision Issues
0,1.355253,1,Malignant,0.050488,III,0,0,0,-1.089675,-1.717548,...,0,0,0,1,0,1,0,0,1,0
1,-1.347627,1,Benign,-0.141399,II,1,1,1,-1.375673,0.739298,...,0,0,0,0,0,0,0,1,0,0
2,-1.060087,1,Benign,0.127742,I,0,0,0,-1.335202,0.402556,...,1,0,0,1,0,0,0,0,1,0
3,-1.175103,1,Malignant,-1.379648,IV,1,0,1,-1.058346,-0.316229,...,0,0,0,1,0,1,0,0,0,0
4,0.262599,0,Benign,-1.023511,I,0,0,1,-0.893014,0.624153,...,0,0,0,0,0,0,0,0,1,0

## 6. Conversión de Variables Ordinales Ⅳ → 4

La variable 'Stage' representa el estadio del tumor usando números romanos (I, II, III, IV). Para que los modelos puedan interpretar correctamente esta información ordinal, se realiza la conversión a valores numéricos enteros usando `.map()`, preservando el orden natural de los estadios.

Esto facilita el análisis y el entrenamiento de modelos que pueden beneficiarse de la información de orden en la variable.

In [ ]:
roman_to_int = {'I': 1, 'II': 2, 'III': 3, 'IV': 4}
df['Stage'] = df['Stage'].map(roman_to_int)

df.head()

,Age,Gender,Tumor_Type,Tumor_Size,Stage,Radiation_Treatment,Surgery_Performed,Chemotherapy,Survival_Rate,Tumor_Growth_Rate,...,Histology_Meningioma,Symptom_1_Nausea,Symptom_1_Seizures,Symptom_1_Vision Issues,Symptom_2_Nausea,Symptom_2_Seizures,Symptom_2_Vision Issues,Symptom_3_Nausea,Symptom_3_Seizures,Symptom_3_Vision Issues
0,1.355253,1,Malignant,0.050488,3,0,0,0,-1.089675,-1.717548,...,0,0,0,1,0,1,0,0,1,0
1,-1.347627,1,Benign,-0.141399,2,1,1,1,-1.375673,0.739298,...,0,0,0,0,0,0,0,1,0,0
2,-1.060087,1,Benign,0.127742,1,0,0,0,-1.335202,0.402556,...,1,0,0,1,0,0,0,0,1,0
3,-1.175103,1,Malignant,-1.379648,4,1,0,1,-1.058346,-0.316229,...,0,0,0,1,0,1,0,0,0,0
4,0.262599,0,Benign,-1.023511,1,0,0,1,-0.893014,0.624153,...,0,0,0,0,0,0,0,0,1,0

## 7. Exportación del Dataset 📦

In [ ]:
import os

os.makedirs("data/processed", exist_ok=True)
df.to_csv("../data/processed/brain_tumor_preprocessed.csv", index=False)